version: '3.8'

services:
  subconverter:
    image: duzefu/clash-converter-subconverter:latest
    container_name: subconverter
    ports:
      - "25500:25500"
    restart: always
    networks:
      - clash-converter

  sub-web:
    image: duzefu/clash-converter-sub-web:latest
    container_name: sub-web
    ports:
      - "8080:80"
    restart: always
    networks:
      - clash-converter
    depends_on:
      - subconverter

networks:
  clash-converter:
    driver: bridge
